Metrics/MethodLength:
  Max: 40

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled:	false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
